### ISSUE TITLE
please update for Plasma 6

### ISSUE THREAD

**Issue by wolftune** [wojnilowicz/workrave-applet#12] opened 2024-03-04 01:42 UTC
I love this, but it won't work in plasma 6. Can it get updated?

**Comment by wojnilowicz** [comment] 2024-03-31 17:16
I've updated my plasmoid to Plasma 6. Here is how you can try it out:
```
git clone -b kf6-port --depth=1 https://github.com/wojnilowicz/workrave-applet.git
cd workrave-applet
kpackagetool6 -t Plasma/Applet --install src
```
I still haven't switched to Plasma 6 so it's mainly untested. The applet should work in the X11 session. Stable Workrave crashes constantly on Wayland. I didn't test the [beta](https://github.com/rcaelers/workrave/releases/tag/v1_11_0_beta_11) version that says it has fixes for Wayland.

**Comment by wolftune** [comment] 2024-04-02 19:06
you would like me to test or might as well wait for the Workrave update? I can test if you are requesting it

**Comment by wojnilowicz** [comment] 2024-04-03 15:56
You asked for a Plasma 6 version of the plasmoid. It's here for you to use it. If plain Workrave works for you, then my plasmoid should work as well. Not requesting anything.

**Comment by wolftune** [comment] 2024-04-03 16:02
I just meant about testing sooner vs later. I very much want to use this, but Workrave itself is not yet working for me, so the full functioning will be both Workrave and this plasmoid. And if you would like me to test the plasmoid even though Workrave is still needing update to support kde-idle, I could do that. Otherwise, I will wait for Workrave to be updated and then test this then.

**Comment by wojnilowicz** [comment] 2024-04-04 19:00
Testing my plasmoid while Workrave is not working won't help me. Thanks anyway.

**Comment by wolftune** [comment] 2024-04-04 19:12
okay, when Workrave is updated to work with KDE 6, I'll happily then use it with your plasmoid

**Comment by jjramsey** [comment] 2024-04-13 16:30
> okay, when Workrave is updated to work with KDE 6, I'll happily then use it with your plasmoid

@wolftune How do you compile the beta Workrave? I know that to get it to work under LabWC, I had to add `-DHAVE_WAYLAND:BOOL=TRUE` to the CMake command line used to configure the build (see https://github.com/rcaelers/workrave/issues/523#issuecomment-2038323700). While LabWC is different from KWin, the two compositors should use the same idle-notify protocol.

**Comment by wolftune** [comment] 2024-04-14 04:01
@jjramsey I would ask that at https://github.com/rcaelers/workrave/discussions not on this issue about the applet
I haven't tested the beta myself yet. I am eager to have it all working but am not able to prioritize testing everything myself at this time. My vague impression is that there's a kde-notify that is distinct from idle-notify but I'm not sure

**Comment by jjramsey** [comment] 2024-04-15 02:10
> I would ask that at https://github.com/rcaelers/workrave/discussions not on this issue about the applet

Just FYI, I wasn't asking for advice on compiling Workrave. I was asking how *you* compile it, because I wanted to know if you had done it correctly. You had commented on the issue about Workrave's Wayland support (https://github.com/rcaelers/workrave/issues/523), so I figured you had at least tried the Workrave beta.

> My vague impression is that there's a kde-notify that is distinct from idle-notify but I'm not sure

FWIW, I had been keeping my eye on the idle-notify protocol, and as far as I can tell, it *started* as a KWin protocol and then got adapted into a proper Wayland one (see the next to last paragraph in https://www.phoronix.com/news/Wayland-Protocols-1.27). It *should* be implemented in KWin now (https://invent.kde.org/plasma/kwin/-/merge_requests/2959).

**Comment by jjramsey** [comment] 2024-04-18 01:04
I can verify that the Plasma 6 version of the applet works for me, using the Workrave beta compiled for Wayland.

**Comment by arturaz** [comment] 2024-05-11 17:35
> I've updated my plasmoid to Plasma 6. Here is how you can try it out:

I want to note that on OpenSUSE Tumbleweed the qdbus executable is called `qdbus6`, not `qtbus-qt6`, so the applet should check for both names probably.

```
arturaz@localhost:~/Software/workrave-applet> qdbus6 org.workrave.Workrave
/
/org
/org/gtk
/org/gtk/Profiler
/org/workrave
/org/workrave/Workrave
/org/workrave/Workrave/UI
/org/workrave/Workrave/Core
/org/workrave/WorkraveApplication
```

**Comment by wojnilowicz** [comment] 2024-05-11 18:10
@arturaz, thank you for this valuable piece of information. I'll be checking for qdbus6 as well.

**Comment by arturaz** [comment] 2024-05-13 12:49
After using it for some time I can confirm that Plasma 6 version works perfectly fine on X11 session as well.

> Information for package workrave:
> ---------------------------------
> Repository     : Main Repository (OSS)
> Name           : workrave
> Version        : 1.10.50-3.2
> Arch           : x86_64
> Vendor         : openSUSE
> Installed Size : 14,1 MiB
> Installed      : Yes
> Status         : up-to-date
> Source package : workrave-1.10.50-3.2.src
> Upstream URL   : http://www.workrave.org
> Summary        : Recovery and prevention of Repetitive Strain Injury program
> Description    : 
>     Workrave is a program that assists in the recovery and prevention of Repetitive Strain Injury (RSI). The program frequently alerts you to take micro-pauses, rest breaks and restricts you to your daily limit.

**Comment by wojnilowicz** [comment] 2024-05-26 16:14
> > I've updated my plasmoid to Plasma 6. Here is how you can try it out:
> 
> I want to note that on OpenSUSE Tumbleweed the qdbus executable is called `qdbus6`, not `qtbus-qt6`, so the applet should check for both names, as otherwise it says "Workrave is not installed".
> 
> ```
> arturaz@localhost:~/Software/workrave-applet> qdbus6 org.workrave.Workrave
> /
> /org
> /org/gtk
> /org/gtk/Profiler
> /org/workrave
> /org/workrave/Workrave
> /org/workrave/Workrave/UI
> /org/workrave/Workrave/Core
> /org/workrave/WorkraveApplication
> ```
> 
> I believe the solution is to add this to `main.qml`:
> 
> ```qml
>   Plasma5Support.DataSource {
>     id: qDBusQt6AlternativeNameCheck
>     engine: 'executable'
>     interval: 0
>     connectedSources: ["qdbus6"]
>     onNewData: function(sourceName, data) {
>       if (!interval)
>         return
>       if (data.stderr.length > 0) {
>       } else {
>         dbusExecutableName = "qdbus6"
>       }
>       workraveCheckDBus.interval = 1
>       interval = 0
>     }
>   }
> ```

qdbus-qt6 is needed on Fedora, so I cannot remove it. I've added a script to the applet to detect the qdbus name used by user's distribution. Here is how you can try it out:
```
git clone -b kf6-port --depth=1 https://github.com/wojnilowicz/workrave-applet.git
cd workrave-applet
kpackagetool6 -t Plasma/Applet --upgrade src
```
if you already have installed my applet, or
```
git clone -b kf6-port --depth=1 https://github.com/wojnilowicz/workrave-applet.git
cd workrave-applet
kpackagetool6 -t Plasma/Applet --install src
```
if you don't have it installed at the moment.

**Comment by wolftune** [comment] 2024-09-10 21:47
Hi, I gave up on waiting for the full Wayland release and had other wayland problems, so I tried switching my system back to x. Workrave is working (not the beta, the normal older version), but the widget is not. I'm seeing the qdbus error message. I'm using KDE Neon.

**Comment by wojnilowicz** [comment] 2024-09-11 17:34
> Hi, I gave up on waiting for the full Wayland release and had other wayland problems, so I tried switching my system back to x. Workrave is working (not the beta, the normal older version), but the widget is not. I'm seeing the qdbus error message. I'm using KDE Neon.

This one? 
> Please make sure that the command `qdbus org.workrave.Workrave` works without issues in your terminal.
Does this command work for you?
If not, then do you have the qt6-tools-dev-tools package installed?
I haven't tested it myself. Just inferring from what I found about their packages.

**Comment by wolftune** [comment] 2024-09-11 18:16
Yes, that message, and it works as in:

```
$ qdbus org.workrave.Workrave
/
/org
/org/workrave
/org/workrave/WorkraveApplication
/org/workrave/Workrave
/org/workrave/Workrave/Menu
/org/workrave/Workrave/Core
/org/workrave/Workrave/UI
/org/gtk
/org/gtk/Profiler
```

I don't have `qt6-tools-dev-tools` but that is a "Dummy transitional" package. I do have `qt6-tools` and I just now added `qt6-tools-dev` though initially I'm seeing no difference.

**Comment by wojnilowicz** [comment] 2024-09-13 18:55
My bad. I wrote a script for detecting a qdbus name that doesn't work on Ubuntu's dash. I just pushed a fix to the kf6-port branch.

You can update your applet as explained in [this](https://github.com/wojnilowicz/workrave-applet/issues/12#issuecomment-2132274581) comment or copy [this](https://github.com/wojnilowicz/workrave-applet/blob/kf6-port/src/contents/script/detect_qdbus.sh) file to your `/home/$USER/.local/share/plasma/plasmoids/org.kde.workraveApplet/contents/script` where $USER is your username.

Thanks a lot for reporting this.

**Comment by wolftune** [comment] 2024-09-13 19:20
Works!! Yay! Guessing I don't need `qt6-tools-dev` after all right?

**Comment by wojnilowicz** [comment] 2024-09-13 19:26
Glad to hear 🙂 I'm not sure about `qt6-tools-dev`. After all, it asked me to install `qtchooser` to have `qdbus`, so maybe it's not needed.

**Comment by wolftune** [comment] 2024-09-16 18:51
qt6-tools-dev not needed indeed, confirming

I think the only thing left to close this issue is to do a normal release

**Comment by wojnilowicz** [comment] 2024-11-03 17:14
The normal release has been done as the 0.4.0 version, so closing now. 
I finally switched to Plasma 6 and it works fine for me, but please let me know, should you have any issues with.

**Closed by wojnilowicz** 2024-11-03 17:14 UTC

**Comment by wolftune** [comment] 2024-11-03 18:06
FYI, I see the README updated, but the GitHub "about" section still says "KDE Plasma 5 applet for displaying Workrave timers."

**Comment by wojnilowicz** [comment] 2024-11-04 15:51
> FYI, I see the README updated, but the GitHub "about" section still says "KDE Plasma 5 applet for displaying Workrave timers."

Indeed 🙂 Thanks!
